---
- hosts: all
  gather_facts: yes
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - /root/.jenkins/workspace/ogbatestpipeline/vars.yaml

  tasks:
    - import_tasks: /root/.jenkins/workspace/ogbatestpipeline/download.yaml
    - import_tasks: /root/.jenkins/workspace/ogbatestpipeline/javacommands.yaml
    - import_tasks: /root/.jenkins/workspace/ogbatestpipeline/extracommands.yaml
